FROM continuumio/miniconda3 as builder
# install mamba
RUN conda install -c conda-forge mamba
# Copy your Conda environment file
COPY MetaQ_env.yml /tmp/MetaQ_env.yml


# Create the environment using Mamba
RUN mamba env create -f /tmp/MetaQ_env.yml

ENV PATH /opt/conda/envs/MetaQ/bin:$PATH


