# Use Ubuntu 22.04 as the base image
FROM agabriel/supercell_multiomics:v1

RUN Rscript -e "install.packages(c('ggseqlogo', 'gprofiler2'), repos = 'https://cran.rstudio.com/', upgrade = 'never')"
RUN Rscript -e "BiocManager::install('OmnipathR', update=FALSE)"


RUN Rscript -e "remove.packages('SuperCellMultiomics')"
RUN Rscript -e "remotes::install_github('GfellerLab/SuperCell@f95f4ae5c14feee53e08571a8d3cd488d4adc89b', upgrade = 'never');library('SuperCell')"

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN conda clean --all -y
RUN rm -rf /opt/conda/pkgs/*

CMD ["bash"]
