name: MetacellAnalysisToolkit
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-seurat=5.1.0
  - r-signac=1.14.0
  - r-rhandsontable=0.3.8
  - bioconductor-glmgampoi=1.14.0
  - bioconductor-aucell=1.24.0
  - r-archr=1.0.3
  - python=3.9.16
  - htslib
  - r-xml=3.99-0.17
  - r-remotes=2.5.0
  - bioconductor-bluster=1.12.0
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-cner=1.38.0
  - r-getopt=1.20.4
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - libxml2
  - r-weights=1.0.4
  - gcc
  - r-biocmanager=1.30.25
  - r-reticulate=1.41.0.1
  - r-irlba=2.3.5.1
  - r-harmony=1.2.3
  - r-argparse=2.2.5
  - r-survey=4.4_2
  - bioconductor-motifmatchr=1.24.0
  - bioconductor-chromvar=1.24.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.5
  - bioconductor-ensdb.hsapiens.v86=2.99.0
  - bioconductor-ensdb.mmusculus.v79=2.99.0
  - bioconductor-tfbstools=1.40.0
  - bioconductor-biovizbase=1.50.0
  - bioconductor-limma=3.58.1
  - r-ggsignif=0.6.4
  - r-sp=2.1.4
  - r-randomforest=4.7-1.1
  - pip:
    - palantir==1.3.3
    - cmake==3.27.0
    - metacells==0.9.0
    - seacells==0.3.3
    - umap-learn==0.5.6
    - magic-impute==3.0.0
