# Script to make analyzis of pseudotime with a gbm_cds ordered 
# command line interface

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------
# http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them


suppressMessages(library(monocle))
suppressMessages(library(getopt))


spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED: 10X data ordered by monocle (.RDS generated by orderCL.R).",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  'firstFilter',   'f',1,"numeric", 'Keep only the genes with at least N = f(X) UMI counts across all samples (X=2 by default) \n(e.g. the total number the gene would have, if it was expressed with a value of X in 1% of the cells). \nAdjust X value according to the dataset (it will depend on the dataset units, e.g. UMI, TPMs???).',
  'secondFilter',  's',1, "numeric", 'Keep the genes that are detected in at least X% of the cells (X=1% by default)',
  'markerTable', 'm',1, "character", "Markers table for the identification of transcription factors",
  'mouseTF','t', 1, 'character', 'Mouse transcription factors list to identify TF in markers table'
), byrow=TRUE, ncol=5);

opt = getopt(spec)



# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("Gene filtering of a gbm cds ordered. For scenic use, two filters")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

#set default arguments values

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}
if (is.null(opt$firstFilter)) {
  opt$firstFilter = 2
}
if (is.null(opt$secondFilter)) {
  opt$secondFilter = 0.01
}

if(!is.null(opt$markerTable)) {
  print("find TF in marker table...")
  markerTable <- read.table(opt$markerTable,sep = "\t",header = T)
  TFlist <- read.table(opt$mouseTF,header = F)
  TF_markers <- data.frame(external_gene_name = markerTable$gene[which(markerTable$gene %in% TFlist$V1)])
  
  #Add tf from bonzanni plus Gfi1b
  TF_bonzani <- data.frame(external_gene_name = c("Spi1","Tal1","Zfpm1","Cbfa2t3","Erg","Fli1","Gata1","Gata2","Hhex","Runx1","Smad6","Zbtb16","Gfi1b"))
  TF_markers <- rbind(TF_markers,TF_bonzani)
  TF_markers <- unique(TF_markers$external_gene_name)
  
  write.table(TF_markers,paste(opt$outdir,"/markers_and_bonzanni_TF.tsv",sep =""),
              sep = "\t",quote = F,row.names = F, col.names = F)
}

gbm_cds <- readRDS(opt$inputRDS)

# Convert to monocle object if necessary (filtering script initially made for monocle)

if(is(gbm_cds) == "Seurat") {
  #It is easier to pass by a monocle object and then reget the seurat object with the genes filtered
  print("input seurat object converting it to monocle")
  DefaultAssay(object = gbm_cds) <- "RNA"
  
  pd <- new("AnnotatedDataFrame", data = gbm_cds@meta.data)
  fd <- new("AnnotatedDataFrame", data = data.frame(gene_short_name = rownames(gbm_cds))) 
  rownames(fd) <- fd$gene_short_name
  
  
  gbm_cds <- newCellDataSet(GetAssayData(gbm_cds,slot = "counts"),
                            phenoData = pd,
                            featureData = fd,
                            lowerDetectionLimit = 0.1,
                            expressionFamily = negbinomial.size())
  
  gbm_cds <- detectGenes(gbm_cds, min_expr = 0.1)
  
  
  
}

exp <- as.matrix(exprs(gbm_cds))
geneShortName<-make.unique(as.character(fData(gbm_cds)$gene_short_name)) # to see between make.unique, remove dup..
rownames(exp) <- geneShortName

nCellsPerGene <- apply(exp, 1, function(x) sum(x>0))
nCountsPerGene <- apply(exp, 1, sum)
summary(nCellsPerGene)
sum(exp>0) / sum(exp==0)

#first filter
minReads <- opt$firstFilter*.01*ncol(exp)
genesLeftMinReads <- names(nCountsPerGene)[which(nCountsPerGene > minReads)]
length(genesLeftMinReads)

#second filter
minSamples <- ncol(exp)*opt$secondFilter
nCellsPerGene2 <- nCellsPerGene[genesLeftMinReads]
genesLeftMinCells <- names(nCellsPerGene2)[which(nCellsPerGene2 > minSamples)]
length(genesLeftMinCells)

t_exp <- t(exp)

print(head(genesLeftMinCells))

write.table(t_exp[,genesLeftMinCells],file = paste(opt$outdir,"/expressionRawCountFilteredForScenic.tsv",sep=""),sep = '\t',quote = F)





