---
title: "Immune stromal multiomic atlas of TME"
author: "Leonard Herault"
date: "`r Sys.Date()`"
output: html_document
---

```{r fig.height=14,fig.width=7, include=FALSE}
library(Seurat)
library(harmony)
library(Signac)
library(SuperCellMultiomics)
library(ggplot2)
library(dplyr)
library(patchwork)


RenameLabels <- function(sobj) {
  sobj$scATOMIC_labels <- sobj$label_integration
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "CD4")] <-"CD4" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "CD8")] <-"CD8" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "killer")] <-"NK" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Fibro")] <-"Fibroblasts" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Endo")] <-"Endothelial" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Dendri")] <-"DC" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Plasma")] <-"Plasma" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "B")] <-"B" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Macro")] <-"Mono/Macro" 
  sobj$scATOMIC_labels[grepl(sobj$scATOMIC_labels,pattern =  "Mast")] <-"Mast" 
  
  sobj$scATOMIC_labels[is.na(sobj$scATOMIC_labels)] <- "Unknown"
  sobj$scATOMIC_labels <- factor(sobj$scATOMIC_labels, levels = c("Fibroblasts","Endothelial","Mono/Macro","DC",
                                                                  "B","Plasma","CD4","CD8","NK","Mast","Unknown"))
  
  
  
  sobj$HTAN <- as.vector(sobj$cell_type)
  sobj$HTAN[sobj$HTAN == "Macrophages"] <- "Macro"
  sobj$HTAN[sobj$HTAN == "B-cells"] <- "B"
  sobj$HTAN[sobj$HTAN == "T-cells"] <- "T"
  
  sobj$HTAN <- factor(sobj$HTAN,  levels = c("Fibroblasts","vSMCs","Pericytes","Endothelial","Macro","DC",
                                             "B","Plasma","T","NK","Mast"))
  
  sobj$cohort <- factor(sobj$cohort,  levels = c("HNSCC","BRCA","SKCM","PDAC","CRC","OV",
                                                 "CESC","UCEC"))
  return(sobj)
}


scAtomic.colors <-  c('#E69F00',"darkgrey",'#E4C755','#0072B2','#D55E00',"#984EA3",'#C1E6F3', "#2CA02C",'#CC79A7','black',  '#712820')
names(scAtomic.colors) <- c("Endothelial","Fibroblasts","DC","Mono/Macro","Plasma","B","CD4","CD8","NK",'Mast','Unknown')

htan.colors <-  c('#E69F00',"darkgrey",'#E4C755','#0072B2','#D55E00',"#984EA3", '#57C3F3','black', "#2CA02C", '#712820')
names(htan.colors) <- c("Endothelial","Fibroblasts","DC","Macro","Plasma","B","T",'Mast',"Pericytes","vSMCs")

major_cell_type_color <- final_palette <-  c('#E69F00',"darkgrey",'#009E73','#E4C755','#0072B2','#D55E00',"#984EA3",'#56B4E9','#CC79A7','#000000')
names(major_cell_type_color) <- c("Endothelial","Fibroblast","Mural","DC","Mono/Macro","Plasma","B","T","NK","Mast")

my.colors <- c('#E5D2DD', '#53A85F', '#F1BB72', '#F3B1A0', '#D6E7A3', '#57C3F3', '#476D87',
               '#E95C59', '#E59CC4', '#AB3282', '#BD956A', '#8C549C', '#9FA3A8', '#E0D4CA',
               '#CCE0F5', '#58A4C3', '#b20000', '#E4C755', '#F7F398', '#AA9A59', '#E63863',
               '#E39A35', '#C1E6F3', '#6778AE', '#91D0BE', '#B53E2B', '#712820', '#DCC1DD',
               '#3A6963', '#D1A33D', '#CCC9E6', '#625D9E', '#68A180', '#5F3D69', '#968175',
               '#D35FB7', '#0072B2', '#00BFC4', '#FF6F00', '#7B3294', '#00A676')



# names(color.clusters) <- levels(atlas.mc$clusters)
# clusters.to.subtypes <- unique(atlas.mc@meta.data[,c("clusters","fine_cell_type")])
# 
# color.fine_cell_type  <-  my37colors[c(1:34)] 
# names(color.fine_cell_type) <- plyr::mapvalues(x= names(color.clusters) ,
#                                                from = as.vector(clusters.to.subtypes$clusters),
#                                                to = as.vector(clusters.to.subtypes$fine_cell_type))

# "#E5D2DD" "#AB3282" "#9FA3A8" "#b20000" "#625D9E" "#5F3D69" "#968175"
```





```{r}
library(Cairo)
options(bitmapType = "cairo")
```


## Cluster annotation
```{r fig.height=6,fig.width=8}

atlas.mc <-  readRDS("../output/whole_atlas/metacells_sup/g10_final/full_atlas_metacells_activities.rds")
atlas.mc <- RenameLabels(atlas.mc)
# atlas.mc[["RNA"]] <- JoinLayers(atlas.mc[["RNA"]] )

DefaultAssay(atlas.mc) <- "RNA"

DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "scATOMIC_labels",label = T,repel = T,cols = scAtomic.colors) + ggtitle("scATOMIC")

```


```{r fig.height=11,fig.width=18}
annotations <- readRDS("../output/whole_atlas/metacells_sup/g10_final/atlas.mc.annotations.rds")

atlas.mc <- AddMetaData(atlas.mc,metadata = annotations[,c('major_cell_type',"fine_cell_type","clusters")])

# atlas.mc$clusters <- factor(atlas.mc$clusters,
#                             levels  =c("0","1","2_0","2_1","2_2","3","4","5",
#                                        "6","7_0","7_1","7_2","8","9","10",
#                                        "11_0","11_1","12_0","12_1","13","14_0","14_1",
#                                        "15","16",
#                                        "17","18","19","20",
#                                        "21_0","21_1","22","23","24",
#                                        "25","26","27"))
# 
# atlas.mc$fine_cell_type <- factor(atlas.mc$fine_cell_type,
#                                   levels = c("Endothelial_PKD1L1","Endothelial_DKK2","Lymph_endo",
#                                              "Fibroblast_COL11A1","Fibroblast_C7","Fibroblast_VIT","Mural",
#                                              "Macro_GPNMB","Macro_SPP1","Macro_SELENOP",
#                                              "Macro_CXCL10","Macro_C3",
#                                              "Mono_VCAN","Mono/Macro_prolif",
#                                              "MonoDC","cDC1","cDC2","DC_RORC","DC3","pDC",
#                                              "Plasma",
#                                              "B","B_prolif",
#                                              "CD4_naive_like_1","CD4_naive_like_2","CD4_Tfh","CD4_Treg","CD8_naive_like",
#                                              "CD8_EM","CD8_Exh","T_prolif",
#                                              "ILC3_like","NK",
#                                              "Mast",
#                                              "Plasma/Macro_doublet","Fibro/Endo_doublet"))

atlas.mc$major_cell_type <- factor(atlas.mc$major_cell_type,
                                   levels = c("Endothelial","Fibroblast","Mural","DC","Mono/Macro","Plasma","B","T","NK","Mast","Doublet"))
# atlas.mc$clusters[atlas.mc$clusters=="6" & atlas.mc$fine_cell_type == "CD8_EM"] <- "6_0"
# atlas.mc$clusters[atlas.mc$clusters=="6" & atlas.mc$fine_cell_type == "CD8_naive_like"] <- "6_1"
# # Some renaming
# table(atlas.mc$fine_cell_type,atlas.mc$clusters)[,c("14","6")]
# atlas.mc$clusters[atlas.mc$clusters=="6" & atlas.mc$fine_cell_type == "CD8_EM"] <- "6_0"
# atlas.mc$clusters[atlas.mc$clusters=="6" & atlas.mc$fine_cell_type == "T_naive_like_2"] <- "6_1"
# 
# atlas.mc$clusters[atlas.mc$clusters=="14" & atlas.mc$fine_cell_type == "MonoDC"] <- "14_0"
# atlas.mc$clusters[atlas.mc$clusters=="14" & atlas.mc$fine_cell_type == "cDC2"] <- "14_1"
# 
# 
# atlas.mc$fine_cell_type[atlas.mc$fine_cell_type=="Myelo_plasma"] <- "Plasmablasts"
# atlas.mc$fine_cell_type[atlas.mc$fine_cell_type=="Macro_unknown"] <- "Macro_C3"
# 
# atlas.mc$fine_cell_type[atlas.mc$fine_cell_type=="T_naive_like_1"] <- "CD4_naive_like"
# atlas.mc$fine_cell_type[atlas.mc$fine_cell_type=="T_naive_like_2"] <- "CD8_naive_like"




```



```{r }


color.clusters <- my.colors
names(color.clusters) <- levels(atlas.mc$clusters)


swp.color <- color.clusters["5"]  
color.clusters["5"] <- color.clusters["13"] 
color.clusters["13"] <- swp.color

swp.color <- color.clusters["8_2"]
color.clusters["8_2"] <- color.clusters["4_0"]
color.clusters["4_0"] <- swp.color

swp.color <- color.clusters["2"]
color.clusters["2"] <- color.clusters["6_1_1"]
color.clusters["6_1_1"] <- swp.color


swp.color <- color.clusters["0"]
color.clusters["0"] <- color.clusters["11"]
color.clusters["11"] <- swp.color

swp.color <- color.clusters["11"]
color.clusters["11"] <- color.clusters["6_1_1"]
color.clusters["6_1_1"] <- swp.color

swp.color <- color.clusters["12"]
color.clusters["12"] <- color.clusters["6_1_1"]
color.clusters["6_1_1"] <- swp.color


swp.color <- color.clusters["8_1"]
color.clusters["8_1"] <- color.clusters["14_1"]
color.clusters["14_1"] <- swp.color

swp.color <- color.clusters["7_2"]
color.clusters["7_2"] <- color.clusters["7_0_0"]
color.clusters["7_0_0"] <- swp.color

swp.color <- color.clusters["20"]
color.clusters["20"] <- color.clusters["23"]
color.clusters["23"] <- swp.color

swp.color <- color.clusters["19"]
color.clusters["19"] <- color.clusters["23"]
color.clusters["23"] <- swp.color

swp.color <- color.clusters["19"]
color.clusters["19"] <- color.clusters["22"]
color.clusters["22"] <- swp.color

swp.color <- color.clusters["12"]
color.clusters["12"] <- color.clusters["16_2"]
color.clusters["16_2"] <- swp.color


swp.color <- color.clusters["3_3"]
color.clusters["3_3"] <- color.clusters["8_1"]
color.clusters["8_1"] <- swp.color

# color.clusters["8"] <- '#D55E00'
# color.clusters["3"] <- "darkgrey"
# color.clusters["11_1"] <- '#E4C755'
# color.clusters["7_0"] <- '#E69F00'
# color.clusters["23"] <- 'black'
# color.clusters["19"] <-  "#2CA02C"
# color.clusters["12_0"] <-  "#984EA3"
# color.clusters["17"] <-  '#CC79A7'
# color.clusters["6"] <-  '#C1E6F3'
# color.clusters["0"] <-  '#0072B2'
# swp.color <- color.clusters["12_1"]
# color.clusters["12_1"] <-  color.clusters["10"]
# color.clusters["10"] <- swp.color 
# 
# swp.color <- color.clusters["22"]
# color.clusters["22"] <-  color.clusters["14_1"]
# color.clusters["14_1"] <- swp.color 
# 
# swp.color <- color.clusters["2_1"]
# color.clusters["2_1"] <-  color.clusters["27"]
# color.clusters["27"] <- swp.color 
# 
# swp.color <- color.clusters["21_1"]
# color.clusters["21_1"] <-  color.clusters["7_2"]
# color.clusters["7_2"] <- swp.color 
# 
# 
# swp.color <- color.clusters["4"]
# color.clusters["4"] <-  color.clusters["7_2"]
# color.clusters["7_2"] <- swp.color 
# 
# swp.color <- color.clusters["22"]
# color.clusters["22"] <-  color.clusters["5"]
# color.clusters["5"] <- swp.color 
# 
# color.clusters["2_1"] <- '#91D0BE'
# color.clusters["26"] <- '#57C3F3'
# color.clusters["25"] <- "#712820"
# color.clusters["7_1"] <- '#D35FB7'
# color.clusters["12_1"] <- "#BD956A"
# color.clusters["5"] <-"#E59CC4"
# color.clusters["15"] <-"#53A85F"
# color.clusters["1"] <- "#E0D4CA" 
# color.clusters["9"] <- "#625D9E"


clusters.to.subtypes <- unique(atlas.mc@meta.data[,c("clusters","fine_cell_type")])

color.fine_cell_type  <-  color.clusters
names(color.fine_cell_type) <- plyr::mapvalues(x= names(color.clusters) ,
                                               from = as.vector(clusters.to.subtypes$clusters),
                                               to = as.vector(clusters.to.subtypes$fine_cell_type))

# color.fine_cell_type <- plyr::mapvalues(from =, to 


atlas.mc$scATOMIC_labels <- factor(atlas.mc$scATOMIC_labels, levels = c("Fibroblasts","Endothelial","Mono/Macro","DC",
                                                                        "B","Plasma","CD4","CD8","NK","Mast","Unknown"))
atlas.mc$HTAN <- factor(atlas.mc$HTAN,  levels = c("Fibroblasts","vSMCs","Pericytes","Endothelial","Macro","DC",
                                                   "B","Plasma","T","NK","Mast"))

p.clusters <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "clusters",label = T,repel = T,cols = color.clusters)

p.fine_cell_type <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "fine_cell_type",label = T,repel = T,cols = color.fine_cell_type)

p.HTAN <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "HTAN",label = T,repel = T,cols = htan.colors) + ggtitle("HTAN")

p.scATOMIC <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "scATOMIC_labels",label = T,repel = T,cols = scAtomic.colors) + ggtitle("scATOMIC")

p.size <- FeaturePlot(atlas.mc,reduction = "wnn.umap",features = "size") + 
  scale_color_distiller(palette = "OrRd",direction = 1,
                        trans = "log10"
  ) + labs(color = "Size")

p.fine_cell_type <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "fine_cell_type",label = T,repel = T,cols = color.fine_cell_type)

p.clusters


```

```{r}
p.fine_cell_type + NoLegend()
```


```{r fig.height=5,fig.width=10}
sc.anno <- readRDS("../output/whole_atlas/metacells/annotation.all.rds") #single_cell annotations saved at the beginning of metacell benchmark integration

sc.anno$HTAN <- as.vector(sc.anno$cell_type)
sc.anno$HTAN[sc.anno$HTAN == "Macrophages"] <- "Macro"
sc.anno$HTAN[sc.anno$HTAN == "B-cells"] <- "B"
sc.anno$HTAN[sc.anno$HTAN == "T-cells"] <- "T"


sc.anno$scATOMIC_labels <- sc.anno$label_scATOMIC
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "CD4")] <-"CD4" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "CD8")] <-"CD8" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "killer")] <-"NK" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Fibro")] <-"Fibroblasts" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Endo")] <-"Endothelial" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Dendri")] <-"DC" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Plasma")] <-"Plasma" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "B")] <-"B" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Macro")] <-"Mono/Macro" 
sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "Mast")] <-"Mast" 

sc.anno$scATOMIC_labels[grepl(sc.anno$scATOMIC_labels,pattern =  "unknown")] <- "Unknown"

names(atlas.mc@misc$membership) <- stringr::str_split_fixed(names(atlas.mc@misc$membership) ,pattern = "\\.",n=2)[,2]
sc.anno$metacell <- atlas.mc@misc$membership[rownames(sc.anno)]

sc.anno$fine_cell_type <- plyr::mapvalues(x=sc.anno$metacell,
                                          from =Cells(atlas.mc),
                                          to = as.vector(atlas.mc@meta.data$fine_cell_type))
sc.anno$metacell_cluster <- plyr::mapvalues(x=sc.anno$metacell,
                                            from =Cells(atlas.mc),
                                            to = as.vector(atlas.mc@meta.data$clusters))

sc.anno$major_cell_type <- plyr::mapvalues(x=sc.anno$metacell,
                                           from =Cells(atlas.mc),
                                           to = as.vector(atlas.mc@meta.data$major_cell_type))

head(sc.anno$fine_cell_type)


# mycolors <- c('#E5D2DD', '#53A85F', '#F1BB72', '#57C3F3', '#F3B1A0', '#D6E7A3', '#476D87',
#               '#E95C59', '#E59CC4', '#AB3282', '#BD956A', '#8C549C',
#               '#9FA3A8', '#5Z8A4C3', "#b20000",'#E4C755', '#F7F398',
#               '#AA9A59', '#E63863', '#E39A35', '#C1E6F3', '#6778AE', '#91D0BE', '#B53E2B',
#               '#712820', '#DCC1DD', '#CCE0F5', '#CCC9E6', '#625D9E', '#68A180',
#               '#968175')
# 
# myColors.scATO <- c('#E5D2DD', '#53A85F', '#F1BB72', '#57C3F3', '#F3B1A0', '#D6E7A3', '#476D87',
#                     '#E95C59', '#E59CC4',"grey")
# 
# myColors.majorType <- c('#E5D2DD', '#53A85F','#CCE0F5', '#F1BB72', '#57C3F3', '#F3B1A0', '#D6E7A3', '#476D87','#E95C59', '#E59CC4'   ,
#                         '#68A180', '#8C549C')
# names(myColors.majorType) <- c("B","Fibroblast","Mural","CD4","CD8","DC","Endothelial","Mono/Macro","ILC","Plasma","Mast","T_prolif")

library(dplyr)
```

Plot metadata atlas




```{r}
library(stringr)
head(atlas.mc@meta.data)
biospecimen <- read.table("/work/FAC/FBM/LLB/dgfeller/scrnaseq/lherault/HTAN_atlas/workflow_level4_data/data/table_data_biospecimen.tsv",sep = '\t',header = T)
participants <- read.table("/work/FAC/FBM/LLB/dgfeller/scrnaseq/lherault/HTAN_atlas/workflow_level4_data/data/table_data_participants.tsv",sep = '\t',header = T)
metadata <- read.table("/work/FAC/FBM/LLB/dgfeller/scrnaseq/lherault/HTAN_atlas/workflow_level4_data/data/HTAN_metadata.tsv",sep = '\t',header = T)
rna.files <- read.csv("/work/FAC/FBM/LLB/dgfeller/scrnaseq/lherault/HTAN_atlas/workflow_level4_data/data/table_rna_files.tsv",sep = '\t',header = T)
rna.files <- rna.files[rna.files$File.Format == "RData",]
rna.files
rna.files$Piece_ID <- str_split_fixed(rna.files$Filename,pattern = "/",n=2)[,2]
rna.files$Piece_ID <- str_split_fixed(rna.files$Piece_ID,pattern = "\\.",n=2)[,1]
rownames(rna.files) <- rna.files$Piece_ID 
rna.files <- rna.files[unique(atlas.mc$Piece_ID),]
length(unique(rna.files$Biospecimen))
biospecimen <- biospecimen[biospecimen$HTAN.Biospecimen.ID %in% unique(rna.files$Biospecimen),]
atlas.mc$HTAN_biospecimen  <- plyr::mapvalues(x = atlas.mc$Piece_ID,from = rna.files$Piece_ID,to = rna.files$Biospecimen)
atlas.mc$Tumor_tissue_type  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                               from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Tumor.Tissue.Type)

atlas.mc$Preservation_method  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                                 from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Preservation.Method)

atlas.mc$Acquisition_method  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                                from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Acquisition.Method.Type)

atlas.mc$Timepoint  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                       from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Timepoint.Label)

atlas.mc$Storage_method  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                            from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Storage.Method)

atlas.mc$Histologic_morphology_code  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                                        from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$Histologic.Morphology.Code)




atlas.mc$Participant_ID  <- plyr::mapvalues(x = atlas.mc$HTAN_biospecimen,
                                            from = biospecimen$HTAN.Biospecimen.ID,to = biospecimen$HTAN.Parent.ID)

atlas.mc$Ethnicity  <- plyr::mapvalues(x = atlas.mc$Participant_ID,
                                       from = participants$HTAN.Participant.ID,to = participants$Ethnicity)

atlas.mc$Treatment_type  <- plyr::mapvalues(x = atlas.mc$Participant_ID,
                                            from = participants$HTAN.Participant.ID,to = participants$Treatment.Type)

atlas.mc$Age_at_diagnosis <- plyr::mapvalues(x = atlas.mc$Participant_ID,
                                             from = participants$HTAN.Participant.ID,to = participants$Age.at.Diagnosis..years.)

atlas.mc$Gender <- plyr::mapvalues(x = atlas.mc$Participant_ID,
                                   from = participants$HTAN.Participant.ID,to = participants$Gender)

atlas.mc$Race <- as.vector(plyr::mapvalues(x = atlas.mc$Participant_ID,
                                           from = participants$HTAN.Participant.ID,to = participants$Race))

atlas.mc$Treatment_outcome <- plyr::mapvalues(x = atlas.mc$Participant_ID,
                                              from = participants$HTAN.Participant.ID,to = participants$Treatment.Outcome)


table(atlas.mc$Race )

table(atlas.mc$Gender )
table(atlas.mc$Tumor_tissue_type )

table(atlas.mc$Treatment_outcome )


table(atlas.mc$Tumor_tissue_type )

unique(biospecimen$HTAN.Parent.ID)

dup.donors <- biospecimen[duplicated(biospecimen$HTAN.Parent.ID),"HTAN.Parent.ID"]
biospecimen[biospecimen$HTAN.Parent.ID%in% dup.donors,]

head(participants$HTAN.Participant.ID)
biospecimen
participants
biospecimen
```

```{r}
atlas.mc$Sex <-  tolower(atlas.mc$Gender)
unique(atlas.mc$Sex)

biospecimen$Sex <-  plyr::mapvalues(x=biospecimen$HTAN.Biospecimen.ID,
                                    from = atlas.mc$HTAN_biospecimen,to = atlas.mc$Sex,warn_missing = F)

biospecimen$Piece_ID <-  plyr::mapvalues(x=biospecimen$HTAN.Biospecimen.ID,
                                         from = atlas.mc$HTAN_biospecimen,to = atlas.mc$Piece_ID,warn_missing = F)

biospecimen$cohort <- plyr::mapvalues(x=biospecimen$HTAN.Biospecimen.ID,
                                      from = atlas.mc$HTAN_biospecimen,to = atlas.mc$cohort,warn_missing = F)

biospecimen$cohort <- plyr::mapvalues(x=biospecimen$HTAN.Biospecimen.ID,
                                      from = atlas.mc$HTAN_biospecimen,to = as.vector(atlas.mc$cohort),warn_missing = F)

grouped.meta.data <- biospecimen %>% 
  group_by(cohort,Tumor.Tissue.Type) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))


# grouped.meta.data$fine_cell_type <- factor(grouped.meta.data$fine_cell_type, levels = levels(atlas.mc$fine_cell_type))
atlas.type.bp <- ggplot(grouped.meta.data,aes(x=cohort,y=perc,fill = Tumor.Tissue.Type)) + 
  geom_bar(stat = "identity",position = "fill")  +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(guide = guide_axis(angle = 0),limits=rev)+ coord_flip()  + theme(legend.position = "bottom",
                                                                                    axis.title.y = element_blank(),
                                                                                    axis.text.y = element_blank(),
                                                                                    legend.title = element_blank())  + ylab("Sample tissue type (%)")


# grouped.meta.data <- biospecimen %>% 
#   group_by(cohort,Sex) %>% 
#   summarise(count = n()) %>% 
#   mutate(perc = count/sum(count))


# grouped.meta.data$fine_cell_type <- factor(grouped.meta.data$fine_cell_type, levels = levels(atlas.mc$fine_cell_type))
# atlas.sex.bp <- ggplot(grouped.meta.data,aes(x=cohort,y=perc,fill = Sex)) + 
#   geom_bar(stat = "identity",position = "fill")  +
#   scale_y_continuous(labels = scales::percent) +
#   scale_x_discrete(guide = guide_axis(angle = 0),limits=rev)+ coord_flip() + theme(legend.position = "bottom",
#                                                                                    axis.title.y = element_blank(),
#                                                                                    axis.text.y = element_blank(),
#                                                                                    legend.title = element_blank()) + ylab("Tissue type (%)")

# atlas.sex.bp


grouped.meta.data <- biospecimen %>% 
  group_by(cohort,Tumor.Tissue.Type) %>% 
  summarise(count = n()) 
grouped.meta.data$cohort <- factor(grouped.meta.data$cohort,levels = c("HNSCC","BRCA","SKCM","PDAC","CRC","OV","CESC","UCEC"))
grouped.meta.data$Tumor.Tissue.Type <- factor(grouped.meta.data$Tumor.Tissue.Type,levels = (c("Normal","Primary","Metastatic")))

n.smp.bp <- ggplot(grouped.meta.data,aes(x=cohort,y=count)) + 
  geom_bar(stat = "identity")  +
  scale_x_discrete(guide = guide_axis(angle = 0),limits=rev)+ coord_flip()  + ylab("N. samples") + theme_classic() +theme(axis.title.y = element_blank(),legend.position = "right",legend.title = element_blank()) 
# +scale_fill_manual(values = hcl.colors(6,palette = "lightgrays")[c(1,4,6)])





```

```{r fig.height=2,fig.width=2}
n.smp.bp

pdf("../pdf_files/Fig4F.pdf",height = 2,width  = 2)
n.smp.bp
dev.off()
```


```{r}
grouped.meta.data <- sc.anno %>% 
  group_by(metacell_cluster, scATOMIC_labels) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))


levels.barplot.cluster <-  unique(atlas.mc@meta.data[,c("clusters","fine_cell_type")])
rownames(levels.barplot.cluster) <- levels.barplot.cluster$fine_cell_type
levels.barplot.cluster <- levels.barplot.cluster[levels(atlas.mc$fine_cell_type),]

grouped.meta.data$metacell_cluster <- factor(grouped.meta.data$metacell_cluster, levels = levels.barplot.cluster$clusters)
aggregated.scATOMIC <-ggplot(grouped.meta.data,aes(x=metacell_cluster,y=perc,fill = scATOMIC_labels)) + 
  geom_bar(stat = "identity",position = "fill") + scale_fill_manual(values = scAtomic.colors) +
  scale_y_continuous(labels = scales::percent,name = "Single-cell annotation") +
  scale_x_discrete(guide = guide_axis(angle = 0),name = "Metacell clusters")
aggregated.scATOMIC
```
```{r}
grouped.meta.data <- sc.anno %>% 
  group_by(metacell_cluster, HTAN) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))


grouped.meta.data$metacell_cluster <- factor(grouped.meta.data$metacell_cluster, levels = levels.barplot.cluster$clusters)
aggregated.HTAN <- ggplot(grouped.meta.data,aes(x=metacell_cluster,y=perc,fill = HTAN)) + 
  geom_bar(stat = "identity",position = "fill") + scale_fill_manual(values = htan.colors) +
  scale_y_continuous(labels = scales::percent,name = "Single-cell annotation") +
  scale_x_discrete(guide = guide_axis(angle = 0),name = "Metacell clusters")


aggregated.HTAN
```
```{r}
p.tissueType <- DimPlot(atlas.mc,reduction = "wnn.umap",group.by = "Tumor_tissue_type",
                        cols = RColorBrewer::brewer.pal(n = 3, name = "Dark2")) + ggtitle("Tumor tissue type")
p.tissueType
```




```{r fig.height=6,fig.width=6.5}
atlas.mc$major_cell_type <- as.vector(atlas.mc$major_cell_type)

atlas.mc$major_cell_type[grepl(x= atlas.mc$fine_cell_type, pattern  = "doublet")] <- as.vector(atlas.mc$fine_cell_type[grepl(x= atlas.mc$fine_cell_type, pattern = "doublet")])
unique(atlas.mc$major_cell_type)
atlas.mc$major_cell_type <- factor(atlas.mc$major_cell_type,levels = c("Endothelial",
                                                                       "Fibroblast",
                                                                       "Mural",
                                                                       "DC",
                                                                       "Mono/Macro",
                                                                       "Plasma",
                                                                       "B",
                                                                       "T",
                                                                       "NK",
                                                                       "Mast",
                                                                       "Fibro/Endo_doublet",
                                                                       "Fibro/Plasma_doublet",
                                                                       "Fibro/T_doublet",
                                                                       "T/Macro_doublet",
                                                                       "Plasma/Macro_doublet"))

cat(c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"),sep = "','") #ggthemes::colorblind_pal()(8)
# major_cell_type_color <- final_palette <- c('#E69F00',"darkgrey",'#009E73','#E4C755','#0072B2','#D55E00',"#984EA3",'#56B4E9','#CC79A7','#000000' )
# major_cell_type_color <- final_palette <- c('#E69F00',"darkgrey",'#009E73','#E4C755','#0072B2','#D55E00',"#984EA3",'#56B4E9','#CC79A7','#000000')
major_cell_type_color_doublet <- c(major_cell_type_color,color.fine_cell_type)
names(major_cell_type_color_doublet)[1:10] <- levels(atlas.mc$major_cell_type)[1:10] 


#   "#F4A582", # Peach
#   "#4DAF4A", # Green
#   "#E78AC3", # Rose
#   "#A6D854", # Lime
#   "#FF7F00", # Orange
#     "#377EB8", # Blue
#       "#A65628", # Brown
# 
#   "#66C2A5", # Aqua
#   "#E41A1C", # Red
#   
#   "#984EA3" # Purple
# )
major.type.with.doublets <- DimPlot(atlas.mc,group.by = "major_cell_type",reduction = "wnn.umap",cols = major_cell_type_color_doublet) + ggtitle("Major types") + theme(legend.position = "bottom")
major.type.with.doublets 


# major.type.no.doublets <- DimPlot(atlas.mc[,!grepl(x = atlas.mc$major_cell_type,pattern = "doublet")],group.by = "major_cell_type",reduction = "wnn.umap",cols = major_cell_type_color)
# major.type.no.doublets
```


```{r fig.height = 6,fig.width = 6.25}
major.type.with.doublets

pdf("../pdf_files/figSN3G.pdf",height = 6,width = 6.25)
major.type.with.doublets
dev.off()
```




```{r fig.height=9,fig.width=7}
figS7AC <- patchwork::wrap_plots(p.clusters + ggtitle("Metacell clusters"),
                                 major.type.with.doublets + theme(legend.position = "right"),
                                 ncol = 1)

figS7AC

pdf("../pdf_files/figS7AC_umaps_all_htan.pdf",height=9,width=7)
figS7AC
dev.off()
```
```{r fig.height=6.75,fig.width=10}
barplot_anno <- wrap_plots(aggregated.scATOMIC + theme(axis.text.x = element_blank(),
                                       axis.title.x = element_blank(),
                                       axis.text.y = element_text(size = 13),
                                       axis.title.y = element_text(size = 15)),
           aggregated.HTAN + theme(axis.text.x = element_text(size = 13),
                                   axis.title.x = element_text(size = 16),
                                   axis.text.y = element_text(size = 13),
                                   axis.title.y = element_text(size = 16))+
             scale_x_discrete(guide = guide_axis(angle = 60),name = 'Metacell clusters'),nrow = 2)
barplot_anno

pdf("../pdf_files/figS7B_barplot_anno.pdf",height=6.75,width=10)
barplot_anno
dev.off()
```




```{r fig.height=9.25,fig.width=6.25}

atlas.mc <- atlas.mc[,!grepl(x = atlas.mc$fine_cell_type,pattern = "doublet")]
gc()



fine.types <- DimPlot(atlas.mc,group.by = "fine_cell_type",reduction = "wnn.umap",cols = color.fine_cell_type,label = T,repel = T) +
  guides(color=guide_legend(ncol=3,override.aes = list(size=4))) +
   ggtitle("Fine cell types")+ theme(legend.position = "bottom")
fine.types 

pdf("../pdf_files/figS7E",height = 9.25,width = 6.25)
fine.types 
dev.off()

# fine.type.no.doublets <- DimPlot(atlas.mc[,!grepl(x = atlas.mc$major_cell_type,pattern = "doublet")],group.by = "fine_cell_type",reduction = "wnn.umap",cols = color.fine_cell_type,label = T,repel = T)
# fine.type.no.doublets
```




```{r  fig.height=3.5,fig.width=5}
major.type.fig5A <- DimPlot(atlas.mc,group.by = "major_cell_type",reduction = "wnn.umap",cols = major_cell_type_color) + ggtitle("Major types") + theme(legend.position = "left")
major.type.fig5A 

pdf("../pdf_files/fig5A.pdf",height = 3.5,width = 5)
major.type.fig5A
dev.off()
```



```{r}
length(unique(color.fine_cell_type))
length(color.fine_cell_type)
length(color.clusters)


my.colors[duplicated(my.colors)]
```

Fig 5B markers




```{r fig.height=5,fig.width=10}
genes <- c("VWF","LUM","NOTCH3","FLT3","CD163","FCRL5","PAX5","CD3G","NCAM1","HDC")
atlas.mc <- atlas.mc[,!grepl(x = atlas.mc$major_cell_type,pattern = "doublet")]

Idents(atlas.mc) <- factor(atlas.mc$major_cell_type,levels = rev(levels(atlas.mc$major_cell_type)))
vln.rna <- VlnPlot.SuperCell(atlas.mc,stack = T,features = genes,
                             assay = "RNA",
                             cols = rev(major_cell_type_color),
                             sort = F,fill.by = "ident") + NoLegend() + theme(axis.title.y = element_blank())

Idents(atlas.mc) <- factor(atlas.mc$major_cell_type,levels = rev(levels(atlas.mc$major_cell_type)))
vln.rna.splitted <- VlnPlot.SuperCell(atlas.mc,stack = F,features = genes,
                                      assay = "RNA",combine = F,flip = T,
                                      cols = rev(major_cell_type_color),
                                      sort = F,fill.by = "ident")


GetVerticalVln <- function(vln,keep.label = F,keep.x.title = T) {
  vln <-vln  + coord_flip() + 
    NoLegend()+
    theme(axis.title.y = element_blank(),
          axis.text.x=element_text(angle=0, hjust=1))
  if (!keep.label) {
    vln <- vln + theme(axis.ticks.y = element_blank(),
                       axis.text.y=element_blank())
  }
  
  if (!keep.x.title) {
    vln <- vln + theme(axis.title.x = element_blank())
  }
  return(vln)
}

library(patchwork)
vln.rna.final <- lapply(vln.rna.splitted, FUN = GetVerticalVln)
vln.rna.final[[1]] <- GetVerticalVln(vln.rna.splitted[[1]],keep.label = T)

wrapped.vln.rna.final <- wrap_plots(vln.rna.final,ncol = length(vln.rna.final),axis_titles  = "collect")

wrapped.vln.rna.final



```


```{r fig.height=5,fig.width=10}
Idents(atlas.mc) <- factor(atlas.mc$major_cell_type,levels = rev(levels(atlas.mc$major_cell_type)))

vln.rna.splitted.sc <- VlnPlot(atlas.mc,stack = F,features = genes,
                               assay = "RNA",combine = F,flip = T,pt.size = 0,
                               cols = rev(major_cell_type_color),
                               sort = F,fill.by = "ident")
vln.rna.final.sc <- lapply(vln.rna.splitted.sc, FUN = GetVerticalVln)
vln.rna.final.sc[[1]] <- GetVerticalVln(vln.rna.splitted.sc[[1]],keep.label = T)

wrapped.vln.rna.final.sc <- wrap_plots(vln.rna.final.sc,ncol = length(vln.rna.final.sc),axis_titles  = "collect")

wrapped.vln.rna.final.sc

```


```{r}
DefaultAssay(atlas.mc) <- "ATAC"
#genes <- c("S100a9","C1qa","Cd3e","Cd19")
Idents(atlas.mc) <- "major_cell_type"

CoveragePlotTSS <- function(atlas.mc,genes,color = major_cell_type_color) {
  TSS <- GetTSSPositions(Annotation(atlas.mc))
  TSS <- TSS[TSS$gene_name%in% genes,]
  
  regions <- lapply(X = genes, function(X){
    TSSgene <- TSS[TSS$gene_name == X]
    region <- Extend(TSSgene,upstream = 500,downstream = 500)
    return(region)
  })
  
  
  
  
  p <- CoveragePlot(
    object = atlas.mc,
    region = regions,ncol = length(regions),
    peaks = FALSE,color = color,
  ) & scale_fill_manual(values = color) 
  
  
  p$patches$plots[[1]] <- p$patches$plots[[1]]  & theme(
    # strip.text.y.left = element_blank(),
    # strip.background = element_blank(),
    # panel.background = element_rect(fill = NA,  color = "black"),
    plot.margin = margin(l = 0,r=0,unit = "pt"),
    #axis.line.y = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x= element_blank(),
    axis.ticks.y = element_blank()
  )& xlab(gsub(x=p$patches$plots[[1]]$labels$x,pattern = " position \\(bp\\)",replacement = "")) 
  
  
  
  for (i in c(2:(length(TSS))-1)) {
    p$patches$plots[[i]] <- p$patches$plots[[i]] & theme(strip.text.y.left = element_blank(),
                                                         strip.background = element_blank(),
                                                         # panel.background = element_rect(fill = NA,  color = "black"),
                                                         plot.margin = margin(l = 0,r=0,unit = "pt"),
                                                         #axis.line.y = element_blank(),
                                                         axis.title.y = element_blank(),
                                                         axis.text.x = element_blank(),
                                                         axis.ticks.x= element_blank(),
                                                         axis.ticks.y = element_blank()
    )& xlab(gsub(x=p$patches$plots[[i]]$labels$x,pattern = " position \\(bp\\)",replacement = ""))
    
    
  }
  
  p$patches$plots[[length(TSS)]] <- p$patches$plots[[length(TSS)]]   & theme(strip.text.y.left = element_blank(),
                                                                             strip.background = element_blank(),
                                                                             # panel.background = element_rect(fill = NA,  color = "black"),
                                                                             plot.margin = margin(l = 0,r=0,unit = "pt"),
                                                                             #axis.line.y = element_blank(),
                                                                             # axis.title.y = element_blank(),
                                                                             axis.text.x = element_blank(),
                                                                             axis.ticks.x= element_blank()
                                                                             # axis.ticks.y = element_blank()
  ) & 
    xlab(gsub(x=p$patches$plots[[i]]$labels$x,pattern = " position \\(bp\\)",replacement = ""))
  
  p$patches$plots[[length(TSS)]][[1]] <- p$patches$plots[[length(TSS)]][[1]] + scale_y_continuous(position = "right",name = "Normalized ATAC signal",
                                                                                                  sec.axis = sec_axis( transform =~.*10, name="Second Axis")) +
    theme(axis.title.y.left  = element_blank(),
          axis.ticks.y.left = element_blank())
  
  p$patches$plots[[length(TSS)]][[2]] <- p$patches$plots[[length(TSS)]][[2]] + theme(axis.title.y  = element_blank())
  
  
  
  
  return(p)
}


p <- CoveragePlotTSS(atlas.mc = atlas.mc,genes = genes)


p
```

```{r fig.height=8,fig.width=9.5}
library(cowplot)
library(patchwork)
fig5B <- wrap_plots(c(vln.rna.final,p$patches$plot),ncol = length(genes),nrow = 2,axes = "collect",guides = "collect",heights = c(1,1.3))
fig5B
pdf("../pdf_files/fig5B.pdf",height=8,width=9.5)
fig5B
dev.off()


```




```{r  fig.height=1.75,fig.width=4.5}
sc.anno <- sc.anno[!sc.anno$major_cell_type == "Doublet",]
grouped.meta.data <- sc.anno %>% 
  group_by(cohort,major_cell_type) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))



grouped.meta.data$major_cell_type <- factor(grouped.meta.data$major_cell_type, levels = rev(c("T","NK","Mono/Macro","DC","B","Plasma","Mast","Endothelial","Fibroblast","Mural")))

grouped.meta.data$cohort <- factor(grouped.meta.data$cohort, levels = c("CRC","CESC","SKCM","PDAC","BRCA","UCEC","OV","HNSCC"))

atlas.type.comp <- ggplot(grouped.meta.data,aes(x=cohort,y=perc,fill = major_cell_type)) + 
  geom_bar(stat = "identity",position = "fill")  +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(guide = guide_axis(angle = 0),limits=rev)+ coord_flip()  + theme(legend.position = "bottom",
                                                                                    legend.title = element_blank())  + ylab("Major types (%)") + NoLegend() + scale_fill_manual(values = major_cell_type_color) + xlab("Cohorts")

atlas.type.comp


pdf("../pdf_files/Fig5C.pdf",height = 1.75,width  = 4.5)
atlas.type.comp
dev.off()
```

# T/NK subtype analysis

```{r fig.height=5,fig.width=6}
label.color  = c("black","black","white","black","black","black","black","black","black","black","white") #order by cluster sizes


umap.Lymph <- DimPlot(atlas.mc[,atlas.mc$major_cell_type%in% c("T","NK")],
                      reduction = "wnn.umap",
                      group.by = c("fine_cell_type"),
                      cols = color.fine_cell_type,label = T,label.box = T,repel =T,
                      label.color  = label.color ) + 
  guides(color = guide_legend(ncol = 1,override.aes = list(size=3)))  + 
  ylim(c(6.5,12.5)) + xlim(c(-1,5.5)) + 
  ggtitle("T/NK subtypes") + NoLegend()
umap.Lymph



```
`
```{r fig.height=3.5,fig.width=7}
genes.lymph <- c("CD3E","CD3G","CD8A","CD4","IL7R",'CXCL13','FOXP3','GZMK',
                 "HAVCR2","MKI67","KIT","RORC","NCAM1")
dotplot.lymph <- DotPlot.SuperCell(atlas.mc[,atlas.mc$major_cell_type%in%c("T","NK")],features = genes.lymph,
                                   assay = "RNA",scale = T,
                                   group.by = "fine_cell_type") + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_y_discrete(limits = rev) + scale_x_discrete(position = "top",guide = guide_axis(angle = 45)) + 
  theme(axis.title.y = element_blank(),                                                                                                              axis.title.x = element_blank()) +
  
  guides(colour=guide_colourbar(title = "Avg. Exp.",override.aes = list(size=5)),
         size = guide_legend(title = "Pct. Exp."))

dotplot.lymph
```
```{r}
genes.dc <- c("FLT3", "IRF8","XCR1","CD1A","CD1C",'RORC',"PRDM16","CCR7","LAMP3","CLEC4C","PTPRS")

dotplot.dc <- DotPlot.SuperCell(atlas.mc[,atlas.mc$major_cell_type%in%c("DC")],features = genes.dc,
                                assay = "RNA",scale = T,
                                group.by = "fine_cell_type") + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_y_discrete(limits = rev) + scale_x_discrete(position = "top",guide = guide_axis(angle = 45)) + 
  theme(axis.title.y = element_blank(),                                                                                                              axis.title.x = element_blank()) +
  
  guides(colour=guide_colourbar(title = "Avg. Exp.",override.aes = list(size=5)),
         size = guide_legend(title = "Pct. Exp."))

dotplot.dc
```
```{r, fig.width=14,fig.height=4}

markers.dc <-  read.csv("../output/whole_atlas/metacells_sup/g10_final/marker_analysis/DC+Mono_Macro//RNA_diff_res.csv",sep = ";",dec = ",")

markers.dc[markers.dc$cluster == "pDC",]
wrap_plots(dotplot.lymph+ ggtitle("T/NK markers"),dotplot.dc+ ggtitle("DC markers"),widths = c(1.25,1))

pdf("../pdf_files/fidS8B_markers_tnk_dc.pdf",height = 4,width = 14)
wrap_plots(dotplot.lymph+ ggtitle("T/NK markers"),dotplot.dc+ ggtitle("DC markers"),widths = c(1.25,1))
dev.off()
```




DC RORC ILC3


```{r}
library(reshape2)

sc.anno$fine_cell_type <- plyr::mapvalues(x=sc.anno$metacell,
                                          from =Cells(atlas.mc),
                                          to = as.vector(atlas.mc@meta.data$fine_cell_type))
# 
# fine.celltype.smp.count <- sc.anno[sc.anno$major_cell_type %in% c("T","NK","Mono/Macro","DC"),] %>% 
#   group_by(fine_cell_type, Sample,.drop = FALSE) %>% 
#   summarise(count = n())
# 
# # fine.celltype.smp.count <- sc.anno[sc.anno$major_cell_type %in%  c("T","NK","Mono/Macro","DC","B","Plasma"),] %>% 
# #   group_by(fine_cell_type, Sample,.drop = FALSE) %>% 
# #   summarise(count = n())
# 
# fine.celltype.smp.count
# 
# count.celltype.mtx <-  acast(fine.celltype.smp.count,Sample~fine_cell_type,fill = 0)
# count.celltype.mtx


```




```{r fig.height=10,fig.width=10}
fine.celltype.smp <- sc.anno[] %>% 
  group_by(fine_cell_type, Sample,.drop = FALSE) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))

fine.celltype.smp
casted.perc <- acast(fine.celltype.smp,Sample~fine_cell_type)
casted.perc[is.na(casted.perc)] <- 0

order.ct <- hclust(dist(t(casted.perc)))

corrplot::corrplot(cor(casted.perc),order = "hclust")
```


```{r fig.height=4.5,fig.width=6}

sc.anno.myelo <- sc.anno[sc.anno$major_cell_type%in% c('Mono/Macro',"DC"),]

count.smp.myelo <- colSums(table(sc.anno.myelo$major_cell_type,sc.anno.myelo$Sample))
smp.kept.myelo <- names(which(count.smp.myelo>100))

sc.anno.t <- sc.anno[sc.anno$major_cell_type%in% c("T","NK"),]
count.smp.t<- colSums(table(sc.anno.t$major_cell_type,sc.anno.t$Sample))
smp.kept.t <- names(which(count.smp.t>100))

smp.kept <- intersect(smp.kept.myelo,smp.kept.t)
# 
# sc.anno.interest <- sc.anno[sc.anno$major_cell_type%in% c("T","NK",'Mono/Macro',"DC"),]
# count.smp<- colSums(table(sc.anno.interest$major_cell_type,sc.anno.interest$Sample))
# smp.kept<- names(which(count.smp>200))
# length(smp.kept)

fine.momacdc.smp <- sc.anno[sc.anno$major_cell_type %in% c('Mono/Macro',"DC") & sc.anno$Sample %in% smp.kept,] %>% 
  group_by(fine_cell_type, Sample,.drop = FALSE) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))

fine.momacdc.smp

myelo.type <- "Macro_CXCL10"


fine.tnk.smp <- sc.anno[sc.anno$major_cell_type %in% c("T","NK")& sc.anno$Sample %in% smp.kept,] %>% 
  group_by(fine_cell_type, Sample,.drop = FALSE) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))

fine.tnk.smp


fine.tnk.momacdc.combined <- rbind(fine.momacdc.smp,fine.tnk.smp)
fine.tnk.momacdc.combined


casted.perc <- acast(fine.tnk.momacdc.combined,Sample~fine_cell_type)
casted.perc[is.na(casted.perc)] <- 0



order.ct <- hclust(dist(t(casted.perc)))

cor.mtx <- Hmisc::rcorr(casted.perc)

cor.mtx.sig <- cor.mtx$r


corrplot::corrplot(cor.mtx.sig[unique(fine.tnk.smp$fine_cell_type),
                               unique(fine.momacdc.smp$fine_cell_type)])


tl.col <- rep("black",length(colnames(casted.perc)))
names(tl.col) <- colnames(casted.perc)


sig.level <-  0.05/(length(unique(fine.tnk.smp$fine_cell_type))*length(unique(fine.momacdc.smp$fine_cell_type))) # bonferonni corr
sig.level

corrplot::corrplot(cor.mtx$r[unique(fine.tnk.smp$fine_cell_type),
                             unique(fine.momacdc.smp$fine_cell_type)],
                   p.mat = cor.mtx$p[unique(fine.tnk.smp$fine_cell_type),
                                     unique(fine.momacdc.smp$fine_cell_type)],
                   tl.srt = 45,is.corr = F,tl.cex	=1,
                   mar = c(0, 0, 2, 0),cl.ratio	=0.3,
                   sig.level = 0.05,
                   insig='blank',order = "hclust",tl.col = "black")


pdf("../pdf_files/figS8_immuneCor.pdf",height=4.5,width=6)

corrplot::corrplot(cor.mtx$r[unique(fine.tnk.smp$fine_cell_type),
                             unique(fine.momacdc.smp$fine_cell_type)],
                   p.mat = cor.mtx$p[unique(fine.tnk.smp$fine_cell_type),
                                     unique(fine.momacdc.smp$fine_cell_type)],
                   tl.srt = 45,is.corr = F,tl.cex	=1,
                   mar = c(0, 0, 2, 0),cl.ratio	=0.3,
                   sig.level = 0.05,
                   insig='blank',order = "hclust",tl.col = "black")

dev.off()
```

```{r}
cor.mtx$r[unique(fine.tnk.smp$fine_cell_type),
          unique(fine.momacdc.smp$fine_cell_type)]
```


```{r}
length(smp.kept)
```


```{r}
cor.mtx.sig["CD8_Exh",
            unique(fine.momacdc.smp$fine_cell_type)]
```


```{r fig.height=5,fig.width=10}
library(ggpubr)

casted.perc.ext <- data.frame(casted.perc)

casted.perc.ext$Cohort <- plyr::mapvalues(x=rownames(casted.perc),
                                          from = sc.anno$Sample,
                                          to = sc.anno$cohort,warn_missing = F)

casted.perc.ext$Type <- plyr::mapvalues(x=rownames(casted.perc),
                                        from = atlas.mc$Sample,
                                        to = atlas.mc$Tumor_tissue_type,warn_missing = F) 

Macro_CXCL9_CD8_prolif <- ggplot(casted.perc.ext,aes(x = Macro_CXCL9, y = CD8_prolif,col = Cohort)) + 
  geom_point()  +
  scale_y_continuous(labels = scales::percent,name = "% of Macro_CXCL9 \nin Mono/Macro/DC") +
  scale_x_continuous(labels = scales::percent,name = "% of CD8_prolif in T/NK") +
  geom_smooth(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD8_prolif),method='lm', formula= y~x) +
  stat_cor(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD8_prolif)) + theme_classic() +
  scale_color_manual(c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"))+ #ggthemes::colorblind_pal()(8)
  scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) #ggthemes::colorblind_pal()(8)

Macro_CXCL9_CD8_prolif 


Macro_CXCL9_CD4_Tfh <-  ggplot(casted.perc.ext,aes(x = Macro_CXCL9, y = CD4_Tfh,col = Cohort)) + geom_point()  +
  scale_y_continuous(labels = scales::percent,name = "% of Macro_CXCL9 \nin Mono/Macro/DC") +
  scale_x_continuous(labels = scales::percent,name = "% of CD4_Tfh in T/NK") +
  geom_smooth(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD4_Tfh),method='lm', formula= y~x) +
  stat_cor(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD4_Tfh)) + theme_classic()+
  scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) #ggthemes::colorblind_pal()(8)


```



```{r}
Macro_CXCL9_CD4_T_prolif <-  ggplot(casted.perc.ext,aes(x = Macro_CXCL9, y = CD4_prolif,col = Cohort)) + geom_point()  +
  scale_y_continuous(labels = scales::percent,name = "% of Macro_CXCL9 \nin Mono/Macro/DC") +
  scale_x_continuous(labels = scales::percent,name = "% of CD4_prolif in T/NK") +
  geom_smooth(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD4_prolif),method='lm', formula= y~x) +
  stat_cor(inherit.aes = F,mapping = aes(x = Macro_CXCL9, y = CD4_prolif)) + theme_classic()+
  scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) #ggthemes::colorblind_pal()(8)
Macro_CXCL9_CD4_T_prolif
```
```{r fig.height=3,fig.width=3}
DC_RORC_ILC3_like <-  ggplot(casted.perc.ext,aes(x = DC_RORC, y = ILC3_like,col = Cohort)) + geom_point()  +
  scale_y_continuous(labels = scales::percent,name = "% of DC_RORC \nin Mono/Macro/DC") +
  scale_x_continuous(labels = scales::percent,name = "% of ILC3_like in T/NK") +
  geom_smooth(inherit.aes = F,mapping = aes(x = DC_RORC, y = ILC3_like),method='lm', formula= y~x) +
  stat_cor(inherit.aes = F,mapping = aes(x = DC_RORC, y = ILC3_like)) + theme_classic()+
  scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) #ggthemes::colorblind_pal()(8)
DC_RORC_ILC3_like
```
```{r fig.height=3.25,fig.width=5.5}
selected.cor <- wrap_plots(DC_RORC_ILC3_like+ theme(legend.position = "bottom"),
           Macro_CXCL9_CD8_prolif + NoLegend())

selected.cor

pdf("../pdf_files/figS8D_selected_corr.pdf",height =3.25,width =5.5)
selected.cor
dev.off()
```

```{r}
# gc()
# genes.lymph <- c("CD3E","CD3G","CD8A","CD4","IL7R",'CXCL13','FOXP3','GZMK',
#                  "HAVCR2","TCF7","SPRY1","BCL6","XCL1","XCL2","MKI67","KIT","RORC","NCAM1")
# dotplot.lymph <- DotPlot.SuperCell(atlas.mc[,atlas.mc$major_cell_type%in%c("T","NK")],features = genes.lymph,
#                                    assay = "RNA",scale = T,
#                                    group.by = "fine_cell_type") + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_y_discrete(limits = rev) + scale_x_discrete(position = "top",guide = guide_axis(angle = 45)) + 
#   theme(axis.title.y = element_blank(),                                                                                                              axis.title.x = element_blank()) +
#   
#   guides(colour=guide_colourbar(title = "Avg. Exp.",override.aes = list(size=5)),
#          size = guide_legend(title = "Pct. Exp."))
# 
# dotplot.lymph
```


```{r}
# dotplot.lymph.ga <- DotPlot.SuperCell(atlas.mc[,atlas.mc$major_cell_type%in%c("T","NK")],features = genes.lymph,
#                                       scale = T,assay = "GA_Signac",
#                                       group.by = "fine_cell_type") + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_y_discrete(limits = rev) + scale_x_discrete(position = "top",guide = guide_axis(angle = 45)) + 
#   theme(axis.title.y = element_blank(),                                                                                                              axis.title.x = element_blank()) +
#   
#   guides(colour=guide_colourbar(title = "Avg. Exp.",override.aes = list(size=5)),
#          size = guide_legend(title = "Pct. Exp."))
# 
# dotplot.lymph.ga
```




```{r fig.height=4.5,fig.width=5}

# n.fine.myelo <- table(as.vector(atlas.mc@meta.data[atlas.mc$major_cell_type%in% c("Mono/Macro","DC"),"fine_cell_type"]))
# 
# n.fine.myelo <- n.fine.myelo[order(n.fine.myelo,decreasing = T)]
# n.fine.myelo
# 
# label.color  = rep("black",length(n.fine.myelo)) #order by cluster sizes
# names(label.color) <- names(n.fine.myelo)
# label.color[["Mono/Macro_prolif"]] <- "white"
# label.color[["DC3"]] <- "white"
# label.color <- c("white", "black", "black", "white" ,"black", "black",
#                  "black" , "white", "white","black", "black" ,"black","white")


label.color <- c("white", "black", "black", "black" ,"black", "black","white",
                 "black" )

umap.macro <- DimPlot(atlas.mc[,atlas.mc$major_cell_type%in% c("Mono/Macro")],
                      reduction = "wnn.umap",
                      group.by = c("fine_cell_type"),
                      cols = color.fine_cell_type,label.color = label.color,
                      label = T,label.box = T,repel =T) + 
  guides(color = guide_legend(ncol = 1,override.aes = list(size=3))) + 
  ylim(c(-9.5,0)) + xlim(c(-10,-1)) +
  ggtitle("Mono/Macro subtypes") + NoLegend()
gc()
umap.macro
```
```{r fig.height=4.5,fig.width=5}
pdf("../pdf_files/Fig5D_umap_macro.pdf",height=4.5,width=5)
umap.macro
dev.off()
```

```{r fig.height=4,fig.width=8}
genes.macro <- c("GPNMB","SETDB2","SPP1","CXCL8","SELENOP","IL12RB2","CGAS","CXCL9","TAZ","INPPL1","VCAN","THBS1","MKI67","TOP2A","FLT3","CLEC10A")
# genes.macro <- markers.mono.macro.top[markers.mono.macro.top$cluster== "Macro_C3","gene"][40:60]

dot.plot.momacdc <- DotPlot.SuperCell(atlas.mc[,atlas.mc$major_cell_type%in% c("Mono/Macro")],features = genes.macro,
                                      assay = "RNA",scale = T,
                                      group.by = "fine_cell_type") + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_y_discrete(limits = rev) + scale_x_discrete(position = "top",guide = guide_axis(angle = 45)) + theme(axis.title.y = element_blank(),                                                                                                              axis.title.x = element_blank()) + 
  guides(colour=guide_colourbar(title = "Avg. Exp.",override.aes = list(size=5)),
         size = guide_legend(title = "Pct. Exp."))


dot.plot.momacdc
```

```{r fig.height=4.5,fig.width=5}

# n.fine.myelo <- table(as.vector(atlas.mc@meta.data[atlas.mc$major_cell_type%in% c("Mono/Macro","DC"),"fine_cell_type"]))
# 
# n.fine.myelo <- n.fine.myelo[order(n.fine.myelo,decreasing = T)]
# n.fine.myelo
# 
# label.color  = rep("black",length(n.fine.myelo)) #order by cluster sizes
# names(label.color) <- names(n.fine.myelo)
# label.color[["Mono/Macro_prolif"]] <- "white"
# label.color[["DC3"]] <- "white"
# label.color <- c("white", "black", "black", "white" ,"black", "black",
#                  "black" , "white", "white","black", "black" ,"black","white")


label.color <- c("black", "black", "black","black","white" )

umap.dc <- DimPlot(atlas.mc[,atlas.mc$major_cell_type%in% c("DC")],
                   reduction = "wnn.umap",
                   group.by = c("fine_cell_type"),
                   cols = color.fine_cell_type,label.color = label.color,
                   label = T,label.box = T,repel =T) + 
  guides(color = guide_legend(ncol = 1,override.aes = list(size=3))) + 
  xlim(c(-9,-2)) + ylim(c(-2,8)) + 
  ggtitle("DC subtypes") + NoLegend()
gc()
umap.dc
```

```{r fig.height=4.25,fig.width=9}
umap.Lymph + umap.dc

pdf("../pdf_files/figS8A_umap_lymph_and_dc.pdf",height=4.25,width=9)
umap.Lymph + umap.dc
dev.off()
```


